name: Daily EV Monitoring

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - run: pip install pandas openpyxl

    - run: python appium-tests/fake_app_data.py
    - run: python python-report/generate_report.py

    - uses: actions/upload-artifact@v4
      with:
        name: EV-Report
        path: EV_Daily_Report.xlsx
        
    - name: Send Email
        run: python python-report/send_email.py
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}