name: Daily EV Monitoring

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install libs
        run: pip install pandas openpyxl

      - name: Install Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: pixel_6
          script: echo "Emulator started"

      - name: Generate fake app data
        run: python appium-tests/fake_app_data.py

      - name: Generate Excel report
        run: python python-report/generate_report.py

      - name: Send Email
        run: python python-report/send_email.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: EV-Report
          path: EV_Daily_Report.xlsx
